name: Reusable SLSA Provenance Generator Worflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@40c607fde64a75eaaa47a6e41e674011d96060f1 # Uses SHA for v3633
